# Generated by Django 4.0.6 on 2022-08-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.TextField()),
                ('movie_url', models.TextField()),
                ('movie_thumbnail', models.ImageField(upload_to='')),
            ],
        ),
    ]
